### PR TITLE
finishgame/cancelgame Improvements; !status, !add, !del reworks; bug fixes

### PR DESCRIPTION
**Pull request by StephenBartos**
This PR is pretty large, ~~but the commit log hopefully breaks it down a bit~~ (nevermind it got out of hand)

## Major Changes:

1. Reworked status to be a singular embed, instead of creating an embed per-category. For any inprogress games, it will now link the channel and show the players in the game:
image
image
2. the IPG embed has been unified, this applies to: the one sent in `config.CHANNEL_ID`, to each player, to the match channel, and in `!status` (the embed in status has a slightly different channel and omits the Match Commands)
image

3 in_progress_game.py:
- Using either finish or cancel will now acquire a lock, which restricts finish or cancel to **only one** being processed at a time (note: this lock is global to the module, so a finish on game_A will block a finish on game_B albeit for a short amount of time). The locks are used within a context manager, so there should be no risk of a deadlock. If a user attempts to finish while a finish is already in progress, they will be notified and their request processed after the lock is yielded.
- confirmation buttons timeout after 10 seconds (to avoid deadlocks), the style has been improved to make it clearer, and all actions (button presses and slash commands) prompt the user for a confirmation
- added a `BaseView` class which includes default error handling for buttons -- this will respond to failed interactions to ensure a response is always sent, since discord.Interactions require them
- consolidated the finish/cancel buttons and slash command logic to use the same functions
4. add, del:
- now looks more like status ~~and shows the players in queue as well as any InProgressGames along with the players in the game~~
image
image
- adding to the waitlist will now give an accurate countdown timer, and the message self deletes after expiration:
image
5. the `in_progress_game` table now includes a `channel_id` field, which corresponds to the ID of the match channel -- I realized this is now necessary for when you want to fetch the channel easily. Now you can use: `channel = bot.get_channel(channel_id)` instead of having to iterate through the channels.

## Minor changes/bug fixes:
- The entire game finish embed will be posted in `config.CHANNEL_ID`
- locked queues will be shown with like "queue_name [locked]" when using `!listqueues`
- `!removecategory` will also remove **all** associated player_category_trueskill records
- in `on_app_command_error`, respond to the interaction if it has not already been responded to, to avoid "this interaction failed" errors
- logging is setup in `config.py` instead now, and any missing `.env` variables will now be logged appropriately
- use the `with Sesssion() as session` context manager wherever applicable to avoid open sessions on exceptions

### CODE REVIEW

**Comment by dlayton66** [comment]
Seems good!  The locking is great, and BaseView + finishgame button callback function are really nice sugar.

The one thing I have mixed feelings about are the confirmation buttons.  I like the implementation, and I think they're good right now because there's no way to fully fix a misfinished game, but if we modify editgamewinner to adjust trueskill as well, it seems easier on the users to occasionally fix a game that was finished incorrectly rather than confirming every time.  What do you think?

**Comment by Andrewki44** [comment]
@dlayton66 just a quick note, if we do go down the road of TrueSkill updates on `!editgamewinner`, then we should try and do the same on `!deletegame` too

**Comment by StephenBartos** [comment]
> The one thing I have mixed feelings about are the confirmation buttons. I like the implementation, and I think they're good right now because there's no way to fully fix a misfinished game, but if we modify editgamewinner to adjust trueskill as well, it seems easier on the users to occasionally fix a game that was finished incorrectly rather than confirming every time. What do you think?

I agree 100% that a proper editgame command would be the better solution -- that way, you could get rid of the confirmations, except for cancelgame. However, the confirmations are fine for now even though they're annoying to the user.

**Comment by dlayton66** [comment]
Right on, I can hop on those in the next week or two.  Shouldn't be too bad

**Pull request merged**
