### PR TITLE
fix: set average_trueskill to average mu and correct category trueskill calculation

### PR DESCRIPTION
**Pull request by dlayton66**
* fix player_category_trueskills to grab trueskills from only in-game players
* switch average_trueskill to be mu.  figure this makes more sense than rank since mu is used for team calculation and that's the value everyone is familiar with

### CODE REVIEW

**Comment by StephenBartos** [comment]
Good catch on the first one, averaging the entire category isn't right.
For the second, why switch back to average mu over average rating? If we want to switch back, then make sure to change the embed's name that uses it.

**Comment by dwayneyuen** [comment]
i dont care too much whether we show avg mu or rank, but agree we should change the label if we do
```
            name="Average Rating", value=round(average_trueskill, 2), inline=False
```

good catch on the category trueskill

**Comment by dlayton66** [comment]
I guess I have trouble understanding what the standalone benefit is of seeing mu-3*sigma.  "there's a 99% chance a player is at least this good" seems like it has fairly limited descriptive value, while mu and sigma alone map directly to concepts we can easily understand.  if I see someone with a high rank, does the bot think they're as good as other people with the same rank?  or have they simply played more games?  no way to know.  my brain makes sense of those concepts easily, but with rank all you can say is there's an arbitrary statistical likelihood that players of the same rank are no worse than some value.

idk, I think it's possible if we used a leaderboard in T1 and I saw those numbers a lot I'd feel differently, but mu-3*sigma just feels kinda meaningless to me.

**Comment by StephenBartos** [comment]
That makes sense, I can see what you mean. Although team making is based entirely on μ, the leaderboard is ordered by TrueSkill Rating. I personally like the idea of thinking in terms of rating instead of μ, since it's a more accurate reflection of your "true skill" 😅
Just μ alone doesn't describe someone's skill level entirely -- or, in this case, the average skill level of a game

Why not order the leader board by μ then?

**Comment by dwayneyuen** [comment]
> since it's a more accurate reflection of your "true skill"

i dont think this is an accurate statement

**Comment by dlayton66** [comment]
^ he said that better than I could.  mu is by definition the bot's best guess of a player's skill level.

I think the reason they did the leaderboard like that is to introduce a stronger element of grinding/climbing the leaderboard.  if it's just based on mu, someone could get really lucky and win their first 5 games and claim the top spot on the leaderboard.  factoring in sigma rewards volume and skill at the same time, so people have to grind and play well if they want to be on top of the board.

the fact that it's a lower bound for everyone's skill is irrelevant afaict, so I guess they just said that so people can attach some kind of meaning to the number?

**Comment by dwayneyuen** [comment]
merging to uppate code, not to close discussion - we can continue discussion in discord! @dlayton66 @StephenBartos

**Pull request merged**
